version: '3.1'

services:
  db:
    image: postgres
    restart: always
    env-file:
      - .env
    ports:
      - 5432:5432

  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    env-file:
      - .env